version: "3.8"

services:
  hodl_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - db:/db
      - ./src:/app
    command: uvicorn admin.main:app --host 0.0.0.0 --port 80 --reload
    env_file: .env
    ports:
      - "8000:80"

  redis:
    image: redis:alpine

volumes:
  db:
