version: "3.8"

services:
  admin_panel: &app
    image: w0rng/hodl:latest
    restart: unless-stopped
    volumes:
      - db:/db
      - ./src:/app
    command: uvicorn admin.main:app --host 0.0.0.0 --port 80 --reload
    env_file: .env
    ports:
      - "8000:80"

  bot:
    <<: *app
    command: python bot/main.py
    ports: []

  redis:
    image: redis:alpine

volumes:
  db:
