[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "w0rng", email = "me@w0rng.ru"},
]
dependencies = [
    "dramatiq>=1.14.1",
    "apscheduler>=3.10.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}
